config/routes.rb
Rails.application.routes.draw do
  resources :add_assignment_student_tables
  resources :grades
  resources :create_grades_tables
  devise_for :admins do
    get '/', to: 'devise/session#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'welcome#index'
  resources :admins

  resources :students
  resources :teachers
  resources :class_rooms do
    resources :students do
      resources :assignments
    end
  end
  resources :class_rooms
  resources :class_rooms do
    resources :gradebooks
    get 'add_student', to: 'class_rooms#new_students'
    post 'new_student', to: 'class_rooms#added_students'
  end
  resources :class_rooms do 
    resources :assignments
    post "class_rooms/:id/assignments/new", to: "assignments#create"
  end

  resources :teachers do
    resources :gradebooks
  end

  resources :students do
    get '/assignments', to: 'students#assignments'
    resources :grades
  end
  resources :students do 
    resources :assignments
  end 
  resources :gradebooks do
    resources :assignments
  end
  resources :assignments do 
    get '/grade', to: 'grades#show'
  end

  resources :grades
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def destroy
    current_admin.invalidate_all_sessions!
    super
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :class_room
    has_many :grades
    has_one :assignment_grade, through: :grades
    has_many :students, through: :class_room 
    validates :title, uniqueness: true

end

app/models/class_room.rb
class ClassRoom < ApplicationRecord
    belongs_to :teacher
    has_many :grades
    has_many :students
    has_many :assignments
    has_many :class_assignments, through: :assignments
    
    validates :subject, presence: true
    accepts_nested_attributes_for :students
    
    

    def add_students(student_obj)
        if self.size > 0
            student_obj.each do |student|
                self.students << student
                self.size = size - 1
                if is_full
                    break
                end
            end
        end
    end

    def is_full
        full = false
        if self.size <= 0
           full = true
        end
        full
    end

    def assignment_to_students
        binding.pry
    end
    
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :assignment
  belongs_to :student
  belongs_to :class_room

end

app/models/gradebook.rb
class Gradebook < ApplicationRecord
    belongs_to :student
end

app/models/qualification.rb
class Qualification < ApplicationRecord
    has_many :teachers
    validates :title, presence: true
    validates :title, uniqueness: true
end

app/models/student.rb
class Student < ApplicationRecord
    has_one :gradebook
    has_many :class_rooms, through: :gradebook
    has_many :grades
    has_many :assignments, through: :grades
    has_many :class_assignments, through: :class_room, source: :gradebook
    has_many :assignment_grades, through: :gradebook, source: :grades
    has_many :class_grades, through: :gradebook, source: :grades
    
    validates :email, uniqueness: true

    def create_gradebook
        self.gradebook.create
    end
    
    def name
        self.first_name + " "+ self.last_name
    end

    def get_assignment(assignment_obj)
        binding.pry
    end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_one :class_room
    has_many :students, through: :class_room
    # has_many :qualifications
    validates :email, uniqueness: true

    def name
        self.first_name + " "+ self.last_name
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
   def index
      binding.pry
   end
   def show
      @admin = Admin.find_by(id: params[:format])
   end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
    def index
        @student =Student.find_by(id:params[:student_id])
    end

    def show
        @grade =  Grade.find_by(assignment_id: params[:assignment_id])
    end

    def update
        binding.pry
        @grade =  Grade.find_by(id: params[:id])
        if @grade.update(update_grade)
            redirect_to class_room_path(@grade.class_room)
        else
            render :show
        end
    end

    private 
    def update_grade
        params.require(:grade).permit(:letter_grade,:class_room_id,:assignment_id,:student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :find_student, only: [:show,:edit,:update,:delete]
    
    def assignments
        
        @student = Student.find_by(id:params[:student_id])
    end

    def index
        @students = Student.all
    end

    def new
        @student = Student.new
    end

    def show
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            @student.gradebook.create
            redirect_to student_path(@student)
        else
            render :new
        end
    end
    def edit
    end
    def update
        if @student.update(student_params)
            redirect_to student_path
        else
            render :edit
        end
    end 
    def find_student
        @student= Student.find_by(id: params[:id])
    end
    private
    def student_params
        params.require(:student).permit(:first_name,:last_name,:age,:email)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def index
        @teachers = Teacher.all
    end
    def new
        @teacher = Teacher.new
    end
    def show
       @teacher = Teacher.find_by(id: params[:id])
       @class_room = ClassRoom.find_by(id: @teacher.class_room)
    end
    def create
        @teacher = Teacher.new(teacher_params)
        binding.pry
        if @teacher.save
            redirect_to teacher_path(@teacher.id)
        else
            render :new
        end
    end

    private

    def teacher_params
        params.require(:teacher).permit(:first_name,:last_name,:email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/class_rooms_helper.rb
module ClassRoomsHelper
end

app/helpers/gradebooks_helper.rb
module GradebooksHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <div class="field">  
    <%= f.label :first_name %>
    <%= f.text_field :first_name %> 
  </div> <br>
  <div class="field">  
    <%= f.label :last_name %>
    <%= f.text_field :last_name %> 
  </div>
  <br>
  <div class='field'>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div> 
  <br>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/students/assignments.html.erb
<h1><%= @student.name %></h1>
<ul>
<% if @student.assignments.empty? %>
    <p>No assignment available</p>
<% else %>
    <% @student.assignments.each do |assignment| %>
        <li><%= assignment.title %> - <%= assignment.grades.find_by(assignment_id: assignment.id).letter_grade %> <%= link_to "Grade Assignment", assignment_grade_path(assignment.id) %></li>
    <% end %>
<% end %>
</ul>

app/views/students/edit.html.erb
<h1>Modify <%= @student.name %></h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h3>Students Attending</h3>
    <ul>
        <% if @students.empty? %>
            <p>No Students Yet</p>
        <% else %>
            <% @students.each do |student| %>
                <p><%= link_to student.name, student_path(student.id) %> - In Development</p>
            <% end %>
        <% end %>
    </ul>
<p><%= link_to "Add Student", new_student_path %></p>

app/views/students/new.html.erb
<h2>New Student</h2>

<%= render 'form' %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<ul>
    <p>Age: <%= @student.age%></p>
    <p>Email: <%= @student.email %></p>
</ul>

<p><%= link_to "Edit Student", edit_student_path  %></p>

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
  <div class="field">  
    <%= f.label :first_name %>
    <%= f.text_field :first_name %> 
  </div>
  <br>
  <div class="field">  
    <%= f.label :last_name %>
    <%= f.text_field :last_name %> 
  </div>
  <br>
  <div class="field">
    <%= f.label :email%>
    <%= f.text_field :email %>
  </div>
  <br>
  
  <br>
  <%= f.submit %>
<% end %>

app/views/teachers/index.html.erb
<h3>Teachers </h3>
    <ul>
        <% if !@teachers %>
            <p>No teachers hired</p>
        <% else %>
            <% @teachers.each do |teacher| %>
                <p><%= link_to teacher.name, teacher_path(teacher.id) %></p>
            <% end %>
        <% end %>
    </ul>
<p><%= link_to "Add New Teacher", new_teacher_path %></p>

app/views/teachers/new.html.erb
<h2>New Teacher</h2>
<%= render 'form' %>

app/views/teachers/show.html.erb
<h2>Hello, <%= @teacher.name %></h2>

<h3>Class</h3>
<% if !@teacher.class_room.nil? %>
   <h4><%= @teacher.class_room.subject %></h4>
        <% if @class_room.students.nil? %>
            <ul>
                <p>No students assigned to class yet</p>
            </ul>
        <% else %>
            <% @teacher.class_room.students.each do |student| %>
                <p><%= link_to student.name, student_assignments_path(student.id) %></p>
            <% end %>
        <% end %>
<% else %>
    <p>No class assigned yet</p>
<% end %>